# Generated by Django 5.1.7 on 2025-05-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name': 'cor', 'verbose_name_plural': 'cores'},
        ),
        migrations.RenameField(
            model_name='cor',
            old_name='descricao',
            new_name='nome',
        ),
    ]
